AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'room conditions

  '
Globals:
  Function:
    Timeout: 3
Resources:
  RoomConditionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://room-condition-api/375d1be0d941b58213837ba0bb8d60ed
      Handler: room-conditions
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /conditions
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
Outputs:
  RoomConditionAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/conditions/
  RoomConditionFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - RoomConditionFunction
      - Arn
  RoomConditionFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - RoomConditionFunctionRole
      - Arn
